version: '3'
services:
  threat-hawk-investigation:
    build: .
    container_name: threat-hawk-investigation
    environment:
      - MEILI_URL=http://threat-hawk-meilisearch:7700
      - ENRICHMENT_URL=http://threat-hawk-enrichment:8000
      - ENCODING_URL=http://threat-hawk-encoding:8000
    restart: always
    ports:
      - "8002:8000"
    networks:
      - threat_hawk_network


# defined my own network here where the db n this is connected
networks:
  threat_hawk_network:
    external: true